#!/bin/bash

OPTIONS=""

if [ ${MEMCACHED_MAX_MEMORY} ]; then
    OPTIONS+=" -m $MEMCACHED_MAX_MEMORY"
fi

if [ ${MEMCACHED_MAX_CONNECTIONS} ]; then
    OPTIONS+=" -c $MEMCACHED_MAX_CONNECTIONS"
fi

if [ ${MEMCACHED_EXTRA_PARAMETERS} ]; then
    OPTIONS+=" $MEMCACHED_EXTRA_PARAMETERS"
fi

set -eu
cmd="$1"; shift

exec $cmd "$@" $OPTIONS
